name: Publish package

on:
  repository_dispatch:
    types:
      - new_version

env:
  PPA: ppa:fragoi/test
  DEBUILD_OPTS: ''

jobs:

  publish:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.event.client_payload.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: fragoi/bash-actions@main

      - name: Provide upstream package
        run: |
          ./bin/provideUpstream meson-installer ${version} \
            || stepExport DEBUILD_OPTS='-sa'

      - name: Download packaging info
        run: |
          downloadTag fragoi/meson-installer v${version} \
            meson-installer_${version}.debian.tar.gz

      - name: Build source package
        uses: fragoi/debuild-action@main
        with:
          ppa: ${{ env.PPA }}
          options: ${{ env.DEBUILD_OPTS }}

      - name: Upload source package
        uses: fragoi/debsign-action@main
        with:
          ppa: ${{ env.PPA }}
          gpg_key: ${{ secrets.GPG_KEY }}
          gpg_pass: ${{ secrets.GPG_PASS }}
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_pass: ${{ secrets.SSH_PASS }}
