name: Publish package

on:
  repository_dispatch:
    types:
      - new_version
  workflow_dispatch:

env:
  PPA: ppa:fragoi/test

jobs:

  publish:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.event.client_payload.version }}
    steps:
      - uses: fragoi/bash-actions@main

      - name: Download source
        run: |
          downloadTag fragoi/meson-installer v${version}

      - name: Build source package
        uses: fragoi/debuild-action@main
        with:
          ppa: ${{ env.PPA }}

      - name: Upload source package
        uses: fragoi/debsign-action@main
        with:
          ppa: ${{ env.PPA }}
          gpg_key: ${{ secrets.GPG_KEY }}
          gpg_pass: ${{ secrets.GPG_PASS }}
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_pass: ${{ secrets.SSH_PASS }}
