name: Publish package

on:
  repository_dispatch:
    types:
      - new_version

run-name: >
  meson-installer
  (${{ github.event.client_payload.version }})
  ${{ github.event.client_payload.dist }}

env:
  PPA: ppa:fragoi/test
  VERSION: ${{ github.event.client_payload.version }}
  DIST: ${{ github.event.client_payload.dist }}
  DISTREV: ${{ github.event.client_payload.distrev }}

jobs:

  publish:
    runs-on: ubuntu-latest
    env:
      DEBUILD_OPTS:
    steps:
      - uses: actions/checkout@v6
      - uses: fragoi/bash-actions@v2

      - name: Provide upstream package
        run: |
          ./bin/provideUpstream meson-installer ${VERSION} \
            || stepExport DEBUILD_OPTS='-sa'

      - name: Download packaging info
        run: |
          downloadTag fragoi/meson-installer v${VERSION} \
            meson-installer_${VERSION}.debian.tar.gz

      - name: Set distribution
        uses: fragoi/debdist-action@v1
        with:
          dist: ${{ env.DIST }}
          distrev: ${{ env.DISTREV }}

      - name: Build source package
        uses: fragoi/debuild-action@v24.0
        with:
          ppa: ${{ env.PPA }}
          options: ${{ env.DEBUILD_OPTS }}

      - name: Upload source package
        uses: fragoi/debsign-action@v1
        with:
          ppa: ${{ env.PPA }}
          gpg_key: ${{ secrets.GPG_KEY }}
          gpg_pass: ${{ secrets.GPG_PASS }}
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_pass: ${{ secrets.SSH_PASS }}
